services:
  - type: web
    name: miniapp-webhook
    env: dotnet
    buildCommand: dotnet build
    startCommand: dotnet MiniAppWebhook.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
